GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/630ed26a7d447ba073f3d9bd

###
DELETE http://localhost:3001/api/persons/630f06f5ab33af1c6382715f

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Rayzzzzzqdaaaazzz",
    "number" : "azasdsad"
}